### ISSUE TITLE
Can't find table if using database schemas

### ISSUE THREAD

**Issue by brandonparsons** [plentz/lol_dba#72]
I'm using database schemas in my app (via `Apartment`). For tables that aren't schema-constrained, they are prefaced by `public`. e..g: `public.users`.  `lol_dba` can't seem to find the tables in this case.

Any way to get this working?

```
BUG: table 'public.users' does not exist, please report this bug.
    BUG: table 'public.map_markers' does not exist, please report this bug.
    
* TIP: if you have a problem with the index name('index name too long') you can solve with the :name option. Something like :name => 'my_index'.
* run `rails g migration AddMissingIndexes` and add the following content:


    class AddMissingIndexes < ActiveRecord::Migration
      def change
        
      end
    end
```

**Comment by plentz** [comment]
@brandonparsons I haven't tried to use `lol_dba` with `apartment` yet, but I think that it would take some effort since I imagine that you want to create migrations for each tenant.

One workaround that should work is to set `schema_search_path` inside your `database.yml` for one of your tenant's schemas and then letting `lol_dba` use it to find the indexes and then replicating those indexes to all your schemas. Makes sense?

**Comment by brandonparsons** [comment]
I couldn't quite get it to work (I didn't get any output after running `lol_dba db:find_indexes`), but that's ok - I suspect my horrible code and not database indexes are going to be the issue for the forseeable future :)

**Comment by plentz** [comment]
@brandonparsons ok :)

closing it for now, if you have any other questions, feel free to ask ;)
